# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tfb5FeYvIjm9HsQOwbqKIRVGxFZeONLU
"""

import pandas as pd
import numpy as np
import re

df = pd.read_excel('dataset_KampusMengajar 1000.csv')

display(df)

# Hapus kolom yang tidak diperlukan
df.drop(df.columns[[0,4,5,6,7,9,10,11,12,13]], axis=1, inplace=True)
display(df)

# Hapus baris kosong
df.dropna(inplace=True)
display(df)

# Ubah format tanggal dan waktu
df['created_at'] = pd.to_datetime(df['created_at'], errors='coerce')
df.dropna(subset=['created_at'], inplace=True)
df['created_at'] = df['created_at'].dt.strftime('%d-%m-%Y')
display(df)

from os import remove
def remove_urls(text):
    return re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)

def remove_special_characters(text):
    return re.sub(r'#[^a-zA-Z0-9\s]', '', text)

#def remove_numbers(text):
    #return re.sub(r'\d+', '', text)

def remove_hashtags_mentions(text):
    return re.sub(r'[@#]\w+', '', text)

def remove_special(text):
    return re.sub(r'[^a-zA-Z0-9\s]', '', text)

def remove_extra_whitespace(text):
    return re.sub(r'\s+', ' ', text).strip()

def to_lowercase(text):
    return text.lower()

def clean_text(text):
    if isinstance(text, str):
        text = remove_urls(text)
        text = remove_special_characters(text)
        text = remove_hashtags_mentions(text)
        text = remove_special(text)
        #text = remove_numbers(text)
        text = to_lowercase(text)
        text = remove_extra_whitespace(text)
    return text

df['Cleaned_FullText'] = df['full_text'].apply(clean_text)
df['Cleaned_Location'] = df['location'].apply(clean_text)
display(df)

df.to_excel('cleaning_file_hasil.xlsx', index=False)
files.download('cleaning_file_hasil.xlsx')